######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 24 17:35:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../usermanager
INCLUDEPATH += .

# Input
