#############################################################################
# Makefile for building: UserManager
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  UserManager.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile UserManager.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fstack-protector-strong -Wformat -Werror=format-security -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -fstack-protector-strong -Wformat -Werror=format-security -g -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = UserManager1.0.0
DISTDIR = /opt/UserManager/.tmp/UserManager1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread  -lcrypt 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = About.cpp \
		Blowfish.cpp \
		editProperties.cpp \
		groupProperties.cpp \
		groups.cpp \
		HashEncode.cpp \
		HashingAlgorithm.cpp \
		HashingFactory.cpp \
		main.cpp \
		MainWindow.cpp \
		Md5.cpp \
		models.cpp \
		myLibb.cpp \
		Settings.cpp \
		sha256.cpp \
		sha512.cpp \
		spc.cpp \
		userproperties.cpp \
		users.cpp qrc_images.cpp \
		moc_About.cpp \
		moc_editProperties.cpp \
		moc_groupProperties.cpp \
		moc_groups.cpp \
		moc_HashingAlgorithm.cpp \
		moc_MainWindow.cpp \
		moc_myLibb.cpp \
		moc_Settings.cpp \
		moc_userproperties.cpp \
		moc_users.cpp
OBJECTS       = About.o \
		Blowfish.o \
		editProperties.o \
		groupProperties.o \
		groups.o \
		HashEncode.o \
		HashingAlgorithm.o \
		HashingFactory.o \
		main.o \
		MainWindow.o \
		Md5.o \
		models.o \
		myLibb.o \
		Settings.o \
		sha256.o \
		sha512.o \
		spc.o \
		userproperties.o \
		users.o \
		qrc_images.o \
		moc_About.o \
		moc_editProperties.o \
		moc_groupProperties.o \
		moc_groups.o \
		moc_HashingAlgorithm.o \
		moc_MainWindow.o \
		moc_myLibb.o \
		moc_Settings.o \
		moc_userproperties.o \
		moc_users.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		UserManager.pro About.h \
		Blowfish.h \
		editProperties.h \
		groupProperties.h \
		groups.h \
		HashEncode.h \
		HashingAlgorithm.h \
		HashingFactory.h \
		IHashing.h \
		MainWindow.h \
		Md5.h \
		models.h \
		myLibb.h \
		pathfile.h \
		Settings.h \
		sha256.h \
		sha512.h \
		spc.h \
		userproperties.h \
		users.h About.cpp \
		Blowfish.cpp \
		editProperties.cpp \
		groupProperties.cpp \
		groups.cpp \
		HashEncode.cpp \
		HashingAlgorithm.cpp \
		HashingFactory.cpp \
		main.cpp \
		MainWindow.cpp \
		Md5.cpp \
		models.cpp \
		myLibb.cpp \
		Settings.cpp \
		sha256.cpp \
		sha512.cpp \
		spc.cpp \
		userproperties.cpp \
		users.cpp
QMAKE_TARGET  = UserManager
DESTDIR       = 
TARGET        = UserManager


first: all
####### Build rules

UserManager: ui_About.h ui_EditProperties.h ui_GroupProperties.h ui_HashingAlgorithm.h ui_mainwindow.h ui_Settings.h ui_UserProperties.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UserManager.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		UserManager.pro \
		resources/images.qrc
	$(QMAKE) -o Makefile UserManager.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
UserManager.pro:
resources/images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile UserManager.pro

qmake_all: FORCE


all: Makefile UserManager

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents About.h Blowfish.h editProperties.h groupProperties.h groups.h HashEncode.h HashingAlgorithm.h HashingFactory.h IHashing.h MainWindow.h Md5.h models.h myLibb.h pathfile.h Settings.h sha256.h sha512.h spc.h userproperties.h users.h $(DISTDIR)/
	$(COPY_FILE) --parents About.cpp Blowfish.cpp editProperties.cpp groupProperties.cpp groups.cpp HashEncode.cpp HashingAlgorithm.cpp HashingFactory.cpp main.cpp MainWindow.cpp Md5.cpp models.cpp myLibb.cpp Settings.cpp sha256.cpp sha512.cpp spc.cpp userproperties.cpp users.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/About.ui ui/EditProperties.ui ui/GroupProperties.ui ui/HashingAlgorithm.ui ui/mainwindow.ui ui/Settings.ui ui/UserProperties.ui $(DISTDIR)/
	$(COPY_FILE) --parents language/el.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: resources/images.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/images/deleteuser2.jpeg \
		resources/images/cancel.png \
		resources/images/floppy.png \
		resources/images/add.png \
		resources/images/edit.png \
		resources/images/user_add.png \
		resources/images/p.jpeg \
		resources/images/deleteuser.jpeg \
		resources/images/language.png \
		resources/images/UserManager.gif \
		resources/images/fax.png \
		resources/images/user_lock.png \
		resources/images/deleteuser1.jpeg \
		resources/images/log.png \
		resources/images/qt.png \
		resources/images/CD.png \
		resources/images/addgroup2.jpeg \
		resources/images/settings.png \
		resources/images/backup.png \
		resources/images/remove.png \
		resources/images/uk.jpeg \
		resources/images/user_unlock.png \
		resources/images/reload.png \
		resources/images/group_add.png \
		resources/images/lock.png \
		resources/images/adduser.jpeg \
		resources/images/addgr.jpeg \
		resources/images/storage.png \
		resources/images/enabled.jpeg \
		resources/images/group.jpeg \
		resources/images/editUser.png \
		resources/images/ok.png \
		resources/images/greek.jpeg \
		resources/images/refresh.png \
		resources/images/editGroup.png \
		resources/images/user_remove.png \
		resources/images/keys.png \
		resources/images/search.png \
		resources/images/scanner.png \
		resources/images/group_remove.png \
		resources/images/quit.png \
		resources/images/user.jpeg
	/usr/lib/qt5/bin/rcc -name images resources/images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++11 -O2 -fstack-protector-strong -Wformat -Werror=format-security -g -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_About.cpp moc_editProperties.cpp moc_groupProperties.cpp moc_groups.cpp moc_HashingAlgorithm.cpp moc_MainWindow.cpp moc_myLibb.cpp moc_Settings.cpp moc_userproperties.cpp moc_users.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_About.cpp moc_editProperties.cpp moc_groupProperties.cpp moc_groups.cpp moc_HashingAlgorithm.cpp moc_MainWindow.cpp moc_myLibb.cpp moc_Settings.cpp moc_userproperties.cpp moc_users.cpp
moc_About.cpp: About.h \
		ui_About.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include About.h -o moc_About.cpp

moc_editProperties.cpp: editProperties.h \
		ui_EditProperties.h \
		ui_HashingAlgorithm.h \
		userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		editProperties.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editProperties.h -o moc_editProperties.cpp

moc_groupProperties.cpp: groupProperties.h \
		ui_GroupProperties.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include groupProperties.h -o moc_groupProperties.cpp

moc_groups.cpp: groups.h \
		pathfile.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include groups.h -o moc_groups.cpp

moc_HashingAlgorithm.cpp: HashingAlgorithm.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include HashingAlgorithm.h -o moc_HashingAlgorithm.cpp

moc_MainWindow.cpp: MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		MainWindow.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_myLibb.cpp: myLibb.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include myLibb.h -o moc_myLibb.cpp

moc_Settings.cpp: Settings.h \
		ui_Settings.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Settings.h -o moc_Settings.cpp

moc_userproperties.cpp: userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include userproperties.h -o moc_userproperties.cpp

moc_users.cpp: users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/UserManager/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/opt/UserManager -I/opt/UserManager -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include users.h -o moc_users.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_About.h ui_EditProperties.h ui_GroupProperties.h ui_HashingAlgorithm.h ui_mainwindow.h ui_Settings.h ui_UserProperties.h
compiler_uic_clean:
	-$(DEL_FILE) ui_About.h ui_EditProperties.h ui_GroupProperties.h ui_HashingAlgorithm.h ui_mainwindow.h ui_Settings.h ui_UserProperties.h
ui_About.h: ui/About.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/About.ui -o ui_About.h

ui_EditProperties.h: ui/EditProperties.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/EditProperties.ui -o ui_EditProperties.h

ui_GroupProperties.h: ui/GroupProperties.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/GroupProperties.ui -o ui_GroupProperties.h

ui_HashingAlgorithm.h: ui/HashingAlgorithm.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/HashingAlgorithm.ui -o ui_HashingAlgorithm.h

ui_mainwindow.h: ui/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

ui_Settings.h: ui/Settings.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/Settings.ui -o ui_Settings.h

ui_UserProperties.h: ui/UserProperties.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ui/UserProperties.ui -o ui_UserProperties.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

About.o: About.cpp About.h \
		ui_About.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o About.o About.cpp

Blowfish.o: Blowfish.cpp Blowfish.h \
		HashEncode.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Blowfish.o Blowfish.cpp

editProperties.o: editProperties.cpp editProperties.h \
		ui_EditProperties.h \
		ui_HashingAlgorithm.h \
		userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		groupProperties.h \
		Settings.h \
		About.h \
		myLibb.h \
		groups.h \
		pathfile.h \
		models.h \
		HashingAlgorithm.h \
		HashingFactory.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editProperties.o editProperties.cpp

groupProperties.o: groupProperties.cpp MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupProperties.o groupProperties.cpp

groups.o: groups.cpp groups.h \
		pathfile.h \
		myLibb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groups.o groups.cpp

HashEncode.o: HashEncode.cpp HashEncode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HashEncode.o HashEncode.cpp

HashingAlgorithm.o: HashingAlgorithm.cpp HashingAlgorithm.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		HashingFactory.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HashingAlgorithm.o HashingAlgorithm.cpp

HashingFactory.o: HashingFactory.cpp HashingFactory.h \
		IHashing.h \
		sha256.h \
		HashEncode.h \
		sha512.h \
		Md5.h \
		Blowfish.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HashingFactory.o HashingFactory.cpp

main.o: main.cpp MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		HashingAlgorithm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

Md5.o: Md5.cpp Md5.h \
		HashEncode.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Md5.o Md5.cpp

models.o: models.cpp models.h \
		editProperties.h \
		ui_EditProperties.h \
		ui_HashingAlgorithm.h \
		userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		groupProperties.h \
		Settings.h \
		About.h \
		myLibb.h \
		groups.h \
		pathfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o models.o models.cpp

myLibb.o: myLibb.cpp myLibb.h \
		pathfile.h \
		userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		models.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myLibb.o myLibb.cpp

Settings.o: Settings.cpp MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		users.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings.o Settings.cpp

sha256.o: sha256.cpp sha256.h \
		HashEncode.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha256.o sha256.cpp

sha512.o: sha512.cpp sha512.h \
		HashEncode.h \
		IHashing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha512.o sha512.cpp

spc.o: spc.cpp spc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spc.o spc.cpp

userproperties.o: userproperties.cpp userproperties.h \
		ui_UserProperties.h \
		users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h \
		HashingFactory.h \
		IHashing.h \
		HashingAlgorithm.h \
		spc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userproperties.o userproperties.cpp

users.o: users.cpp users.h \
		MainWindow.h \
		ui_mainwindow.h \
		ui_UserProperties.h \
		ui_EditProperties.h \
		ui_GroupProperties.h \
		ui_Settings.h \
		ui_About.h \
		userproperties.h \
		editProperties.h \
		ui_HashingAlgorithm.h \
		myLibb.h \
		groupProperties.h \
		Settings.h \
		About.h \
		groups.h \
		pathfile.h \
		models.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o users.o users.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_About.o: moc_About.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_About.o moc_About.cpp

moc_editProperties.o: moc_editProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editProperties.o moc_editProperties.cpp

moc_groupProperties.o: moc_groupProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groupProperties.o moc_groupProperties.cpp

moc_groups.o: moc_groups.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groups.o moc_groups.cpp

moc_HashingAlgorithm.o: moc_HashingAlgorithm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HashingAlgorithm.o moc_HashingAlgorithm.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_myLibb.o: moc_myLibb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myLibb.o moc_myLibb.cpp

moc_Settings.o: moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Settings.o moc_Settings.cpp

moc_userproperties.o: moc_userproperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userproperties.o moc_userproperties.cpp

moc_users.o: moc_users.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_users.o moc_users.cpp

####### Install

install_installfiles: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin/ || mkdir -p $(INSTALL_ROOT)/usr/bin/
	-$(QINSTALL_PROGRAM) /opt/UserManager/UserManager $(INSTALL_ROOT)/usr/bin/UserManager

uninstall_installfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/bin/UserManager
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_installfiles  FORCE

uninstall: uninstall_installfiles  FORCE

FORCE:

