######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 30 23:51:33 2017
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = QCombo_Test
DEPENDPATH += . language resources tests ui
INCLUDEPATH += .

# Input
HEADERS += About.h \
           editProperties.h \
           groupProperties.h \
           groups.h \
           MainWindow.h \
           models.h \
           myLibb.h \
           pathfile.h \
           Settings.h \
           userproperties.h \
           users.h
FORMS += ui/About.ui \
         ui/EditProperties.ui \
         ui/GroupProperties.ui \
         ui/mainwindow.ui \
         ui/Settings.ui \
         ui/UserProperties.ui
SOURCES += About.cpp \
           editProperties.cpp \
           groupProperties.cpp \
           groups.cpp \
           main.cpp \
           MainWindow.cpp \
           models.cpp \
           myLibb.cpp \
           Settings.cpp \
           userproperties.cpp \
           users.cpp \
           tests/Minimaltest.cpp
RESOURCES += resources/images.qrc
TRANSLATIONS += language/el.ts
