######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 25 09:10:09 2017
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += Default.pro
